# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zcJUsZXfjrK9jr10KqHejwowQt5CaFbR
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import geopandas as gpd

# create raster data
single_band = np.random.randint(0, 100, size=(100, 100))*255
second_band = np.random.randint(0, 100, size=(100, 100))*255
third_band = np.random.randint(0, 100, size=(100, 100))*255

 #combine the band
raster_data = np.dstack((single_band, second_band, third_band))

 # Plot the raster
plt.imshow(raster_data)
plt.show()